"""运行时调度与自动回复策略常量。"""

from __future__ import annotations


PRIORITY_ORDER: dict[str, int] = {
    "auto_reply": 1,
    "add_friend": 2,
    "timed_send": 3,
}

PENDING_STALE_SECONDS = 30.0
UI_LOCK_STALE_SECONDS = 300.0

AUTO_REPLY_POLL_INTERVAL_S = 2.0
AUTO_REPLY_ACTIVE_COOLDOWN_MIN_S = 2.0
AUTO_REPLY_ACTIVE_COOLDOWN_MAX_S = 3.0
AUTO_REPLY_UNREAD_COOLDOWN_MIN_S = 2.0
AUTO_REPLY_UNREAD_COOLDOWN_MAX_S = 3.0
AUTO_REPLY_SKIP_FRIENDS = "微信游戏,微信团队,腾讯新闻,订阅号消息,服务通知"


__all__ = [
    "AUTO_REPLY_ACTIVE_COOLDOWN_MAX_S",
    "AUTO_REPLY_ACTIVE_COOLDOWN_MIN_S",
    "AUTO_REPLY_POLL_INTERVAL_S",
    "AUTO_REPLY_SKIP_FRIENDS",
    "AUTO_REPLY_UNREAD_COOLDOWN_MAX_S",
    "AUTO_REPLY_UNREAD_COOLDOWN_MIN_S",
    "PENDING_STALE_SECONDS",
    "PRIORITY_ORDER",
    "UI_LOCK_STALE_SECONDS",
]
