"""wechat_bot 通用默认值与存储辅助。"""

from .defaults import (
    BOT_GUI_SETTINGS_APP,
    BOT_GUI_SETTINGS_ORG,
    DEFAULT_ADD_FRIEND_API_PATH,
    DEFAULT_ADD_FRIEND_INTERVAL_MAX_MINUTES,
    DEFAULT_ADD_FRIEND_INTERVAL_MAX_SECONDS,
    DEFAULT_ADD_FRIEND_INTERVAL_MIN_MINUTES,
    DEFAULT_ADD_FRIEND_INTERVAL_MIN_SECONDS,
    DEFAULT_ADD_FRIEND_SOURCE_TEXT,
    DEFAULT_AUTO_REPLY_TEXT,
    DEFAULT_TIMED_SEND_MESSAGE,
    FRIEND_LIST_CACHE_FILENAME,
    MIN_ADD_FRIEND_INTERVAL_MINUTES,
    MIN_WECHAT_VERSION,
    SELF_PROFILE_CACHE_FILENAME,
    SHORTLINK_RULE_FILENAME,
)
from .auto_reply import (
    AUTO_REPLY_CACHE_FILENAME,
    AUTO_REPLY_RECENT_CACHE_FILENAME,
    AUTO_REPLY_SELF_SENT_CACHE_FILENAME,
    RepliedCache,
    RuleList,
    SelfSentCache,
    load_keyword_rule_pairs,
    load_replied_cache,
    load_self_sent_cache,
    save_replied_cache,
    save_self_sent_cache,
)
from .json_store import load_json_dict, load_json_list, write_json_file

__all__ = [
    "AUTO_REPLY_CACHE_FILENAME",
    "AUTO_REPLY_RECENT_CACHE_FILENAME",
    "AUTO_REPLY_SELF_SENT_CACHE_FILENAME",
    "BOT_GUI_SETTINGS_APP",
    "BOT_GUI_SETTINGS_ORG",
    "DEFAULT_ADD_FRIEND_API_PATH",
    "DEFAULT_ADD_FRIEND_INTERVAL_MAX_MINUTES",
    "DEFAULT_ADD_FRIEND_INTERVAL_MAX_SECONDS",
    "DEFAULT_ADD_FRIEND_INTERVAL_MIN_MINUTES",
    "DEFAULT_ADD_FRIEND_INTERVAL_MIN_SECONDS",
    "DEFAULT_ADD_FRIEND_SOURCE_TEXT",
    "DEFAULT_AUTO_REPLY_TEXT",
    "DEFAULT_TIMED_SEND_MESSAGE",
    "FRIEND_LIST_CACHE_FILENAME",
    "MIN_ADD_FRIEND_INTERVAL_MINUTES",
    "MIN_WECHAT_VERSION",
    "RepliedCache",
    "RuleList",
    "SELF_PROFILE_CACHE_FILENAME",
    "SelfSentCache",
    "SHORTLINK_RULE_FILENAME",
    "load_keyword_rule_pairs",
    "load_json_dict",
    "load_json_list",
    "load_replied_cache",
    "load_self_sent_cache",
    "save_replied_cache",
    "save_self_sent_cache",
    "write_json_file",
]
